{% set name = "usgscsm" %}
{% set version = "2.0.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  - folder: .
    url: https://github.com/DOI-USGS/{{ name }}/archive/{{ version }}.tar.gz
    sha256: 2f2b49fc74b6f2eef92839737315be7585b81331d78592bffdf04e31611e8eaf

  # submodules
  - folder: ale
    url: https://github.com/DOI-USGS/ale/archive/0.10.0.zip
    sha256: d2cecca296de5c44245f0471cf5a3e835fb4792cc9fba24ab9f29822dc67338f
  - folder: csm
    url: https://github.com/USGS-Astrogeology/csm/archive/c78dbba3731432249a75db9fdd7415b292d46715.zip
    sha256: e3eb35fbc27df94d6432c66a93b1dd140a9e93d6897c9107d5a99ab0557e99ea
  - folder: gtest
    url: https://github.com/google/googletest/archive/aee0f9d9b5b87796ee8a0ab26b7587ec30e8858e.zip
    sha256: 04a1751f94244307cebe695a69cc945f9387a80b0ef1af21394a490697c5c895
  - folder: json
    url: https://github.com/nlohmann/json/archive/1a521cbd3657eea6ba90cded2aecca93e3cd78d4.zip
    sha256: 3bc24b2490e91285b66211d3763bb8db3d3fd447f24ae35d82279fcafa60e3d5

build:
  number: 0
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('cxx') }}
    - cmake >=3.10
    - make
    - nlohmann_json
    - eigen
  host:
    - csm
    - vc  # [win]
  run:
    - csm

test:
  commands:
    - test -e $PREFIX/lib/csmplugins/libusgscsm${SHLIB_EXT}  # [unix]
    - if not exist %LIBRARY_BIN%\usgscsm.dll exit 1  # [win]

about:
  home: http://github.com/DOI-USGS/usgscsm
  license: CC0-1.0
  license_file: LICENSE.md
  summary: USGS Astrogeology developed Community Sensor Model implementations

  description: |
    The USGS Astrogeology CSM compliant sensor models for surface planetary
    science applications.
  dev_url: https://github.com/DOI-USGS/usgscsm

extra:
  recipe-maintainers:
    - jlaura
    - acpaquette
    - chkim-usgs
    - Kelvinrr
