{% set name = "usgscsm" %}
{% set version = "1.6.0_asp3.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  git_url: git@github.com:oleg-alexandrov/usgscsm.git
  git_tag: a7cb808

build:
  number: 0
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('cxx') }}
    - cmake

  host:
    - ale 0.8.5.*
    - csm 3.0.3.3.*
    - nlohmann_json 3.10.5

  run:
    - ale 0.8.5.*
    - csm 3.0.3.3.*
    - nlohmann_json 3.10.5

test:
  commands:
    - test -e $PREFIX/lib/libusgscsm${SHLIB_EXT}  # [unix]
    - if not exist %LIBRARY_BIN%\usgscsm.dll exit 1  # [win]

about:
  home: http://github.com/USGS-Astrogeology/usgscsm
  license: Unlicense
  license_file: license.txt
  summary: USGS Astrogeolgoy developed Community Sensor Model implementations

  description: |
    The USGS Astrogeology CSM compliant sensor models for surface planetary
    science applications.
  dev_url: https://github.com/USGS-Astrogeology/usgscsm

extra:
  recipe-maintainers:
    - jlaura
    - jessemapel
