{% set name = "usgscsm" %}
{% set version = "1.5.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  git_url: git@github.com:oleg-alexandrov/usgscsm.git
  git_tag: b6c0a29

build:
  number: 0
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('cxx') }}
    - cmake >=3.15
  host:
    - csm
    - ale
    - nlohmann_json
    - vc  # [win]
  run:
    - ale
    - nlohmann_json
    - csm

test:
  commands:
    - test -e $PREFIX/lib/libusgscsm${SHLIB_EXT}  # [unix]
    - if not exist %LIBRARY_BIN%\usgscsm.dll exit 1  # [win]

about:
  home: http://github.com/USGS-Astrogeology/usgscsm
  license: Unlicense
  license_file: license.txt
  summary: USGS Astrogeolgoy developed Community Sensor Model implementations

  description: |
    The USGS Astrogeology CSM compliant sensor models for surface planetary
    science applications.
  dev_url: https://github.com/USGS-Astrogeology/usgscsm

extra:
  recipe-maintainers:
    - jlaura
    - jessemapel
