{% set name = "usgscsm" %}
{% set version = "1.6.0_asp3.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  git_url: git@github.com:oleg-alexandrov/usgscsm.git
  git_tag: 214170e

build:
  number: 0
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('cxx') }}
    - cmake>=3.15

  host:
    - ale>=0.8.8
    - csm 3.0.3.3.*
    - nlohmann_json >=3.11,<3.12.0a0
    - eigen 3.4.0

  run:
    - ale>=0.8.8
    - csm 3.0.3.3.*
    - nlohmann_json >=3.11,<3.12.0a0

test:
  commands:
#    - test -e $PREFIX/lib/libusgscsm${SHLIB_EXT}  # [unix]
#    - if not exist %LIBRARY_BIN%\usgscsm.dll exit 1  # [win]

about:
  home: http://github.com/USGS-Astrogeology/usgscsm
  license: Unlicense
  license_file: license.txt
  summary: USGS Astrogeolgoy developed Community Sensor Model implementations

  description: |
    The USGS Astrogeology CSM compliant sensor models for surface planetary
    science applications.
  dev_url: https://github.com/USGS-Astrogeology/usgscsm

extra:
  recipe-maintainers:
    - jlaura
    - jessemapel
