travis:
  secure:
    BINSTAR_TOKEN: aeHKFA+HZXiexEVgMnfOyxffxfiUWyMQ9SAO84DZ81fTzEGrz74iIbt6DzdX8Qd2hH8+phJAG26EJNlBk413mG+HI3QxBBqIKbd3yWEeH/OXQrczW7jQae7i+O51TPkf4DRWpGd9OmDsd0Y132br1BXxU70u567UwgmlHCBb3y3wu1Xcx7HgviuAQECfzWBq5wsVtBIByUh3PqgQj+yY1fLknYgQ4nVwxpcFj+XUDLw/3FZq4HmePoivVeLyavtif3k7IiBCUbQftyYgADJ9VID1WlQBi4ruhUbZOp6kC/MmaaMhWgp0FBQh81+t2Bd2rgxjvjGGqczyJSOEe+mfM11cpIsKfvivyaoFW49AsuKzuxv57ziJr5L12nfHB8wCanV66Mz6sUrqBZ2b9Zc6T3oiyJc0bU0BNDC//gb91sOTuyfFxTUahQvCiPwyCeV28Gk2lijKC3OkL2pa7fovVBXrJfab2uls30PjVV6ScOz+c02cjdFGKFf6Z/CIphKtF9iMgNEah9GVgQrdnq4uM0SZhXql7Q3dlvOaMGsdFCywmXcmeELGKjlAVcY0qObjBrxpTdGYAP7KUwQpZB/uBRpscJRdo2cCpMnZpBG9ecpAT3Yx9nXWUGx3JI3YWfdueHoM39t17lw0pjww2Gx35bIgzctSyDUDqdM7cIFMrs8=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
